### ISSUE TITLE
Comment for m1t1

### ISSUE THREAD

**Issue by xeniyad** [PerizatK/.Net-mentoring-D0-D1#1]
It is better to improve task by clean code principles.
I recommend you to change Person class to static one calls PersonUtils, for example and rename method GetValue to GetGreetingForName
Or as another option make name as a private readonly property and pass it over class constructor. Get value is also recommended to change to GetGreeting in this case.
The main idea is to make easier to understand purposes of each class, property and method.

**Comment by PerizatK** [comment]
> 
> 
> It is better to improve task by clean code principles.
> I recommend you to change Person class to static one calls PersonUtils, for example and rename method GetValue to GetGreetingForName
> Or as another option make name as a private readonly property and pass it over class constructor. Get value is also recommended to change to GetGreeting in this case.
> The main idea is to make easier to understand purposes of each class, property and method.

Implemented both recommendations
